from . import (
    admin,
    auth,
    bookings,
    estars,
    feed,
    messages,
    notifications,
    players,
    reviews,
    settings,
    subscriptions,
    users,
    wallet,
)

routers = [
    auth.router,
    users.router,
    players.router,
    bookings.router,
    messages.router,
    reviews.router,
    feed.router,
    wallet.router,
    notifications.router,
    subscriptions.router,
    estars.router,
    admin.router,
    settings.router,
]
